name: the-hask-runner
version: '0.1.0'
github: Akvinikym/the-hask-runner
license: Apache-2.0
category: Game
synopsis: An infinite runner
description: An infinite runner
maintainer: Pavel, Oleg, Nikita, Yuri
copyright: 2018 PONY
data-files: []

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall -fno-warn-type-defaults

dependencies:
    - base >=4.7 && <5
    - aeson
    - animate
    - bytestring
    - containers
    - key-state
    - linear
    - lens
    - mtl
    - safe
    - safe-exceptions
    - sdl2
    - sdl2-image
    - sdl2-mixer
    - sdl2-ttf
    - StateVar
    - text
    - text-conversions
    - random 

default-extensions:
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- OverloadedStrings

library:
  source-dirs: game

executables:
  the-hask-runner:
    dependencies:
    - the-hask-runner
    - base >=4.7 && <5
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
